/// Flutter icons NoticeIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NoticeIcons
///      fonts:
///       - asset: fonts/NoticeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NoticeIcons {
  NoticeIcons._();

  static const _kFontFam = 'NoticeIcons';
  static const String? _kFontPkg = null;

  static const IconData ic_more = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_waste_bin = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_pencil = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
